// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A flow to provide feedback on user's answers to AI-generated interview questions.
 *
 * - aiInterviewFeedback - A function that handles the interview question and feedback process.
 * - AIInterviewFeedbackInput - The input type for the aiInterviewFeedback function.
 * - AIInterviewFeedbackOutput - The return type for the aiInterviewFeedback function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const AIInterviewFeedbackInputSchema = z.object({
  question: z.string().describe('The AI-generated interview question.'),
  answer: z.string().describe('The user\s answer to the interview question.'),
});
export type AIInterviewFeedbackInput = z.infer<typeof AIInterviewFeedbackInputSchema>;

const AIInterviewFeedbackOutputSchema = z.object({
  feedback: z.string().describe('AI feedback on the user\'s answer (correct/incorrect and explain why).'),
});
export type AIInterviewFeedbackOutput = z.infer<typeof AIInterviewFeedbackOutputSchema>;

export async function aiInterviewFeedback(input: AIInterviewFeedbackInput): Promise<AIInterviewFeedbackOutput> {
  return aiInterviewFeedbackFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiInterviewFeedbackPrompt',
  input: {
    schema: z.object({
      question: z.string().describe('The AI-generated interview question.'),
      answer: z.string().describe('The user\'s answer to the interview question.'),
    }),
  },
  output: {
    schema: z.object({
      feedback: z.string().describe('AI feedback on the user\'s answer (correct/incorrect and explain why).'),
    }),
  },
  prompt: `You are an AI interview coach providing feedback to a user answering a JavaScript interview question.

  Question: {{{question}}}
  Answer: {{{answer}}}

  Provide detailed feedback on the user's answer, including whether it is correct or incorrect and why.  Be specific. Focus on where the user is doing well and where they can improve.
  `,
});

const aiInterviewFeedbackFlow = ai.defineFlow<
  typeof AIInterviewFeedbackInputSchema,
  typeof AIInterviewFeedbackOutputSchema
>(
  {
    name: 'aiInterviewFeedbackFlow',
    inputSchema: AIInterviewFeedbackInputSchema,
    outputSchema: AIInterviewFeedbackOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
